[package]
name = "dynamic_voxels"
version = "0.1.0"
edition = "2024"

[lints.rust]
unused = "allow"

[lib]
name = "reload"
path = "src/reload.rs"
crate-type = ["rlib", "dylib"]

[dependencies]
octa-force = { path = "../octa-force-rs" }
# octa-force = { version = "0.2.3", git = "https://github.com/MaartenBehn/octa-force-rs" }
fastrand = "2.2.0"
# glsl_compiler = { path = "../glsl_compiler" }
glsl_compiler = { version = "0.1.4", git = "https://github.com/MaartenBehn/glsl_compiler" }
simple-easing = "1.0.1"

feistel-permutation-rs = { git="https://github.com/MaartenBehn/permutation-rs.git", version = "0.1.5"}
kiddo = "5.0.3"
fast_poisson = { path="../fast_poisson", features = ["single_precision"]}
#fast_poisson = { git="https://github.com/MaartenBehn/fast_poisson.git", version = "1.0.3", features = ["single_precision"]}

# Graphs
egui-graph-edit = "0.6.0"

slotmap = "1.0.7"

unpack_method = { path = "../unpack_method" }
# unpack_method = { version = "0.1.0", git = "https://github.com/MaartenBehn/unpack_method" }
