#pragma once

#ifndef VOXELS_PER_METER
#define VOXELS_PER_METER 10
#endif

#ifndef METERS_PER_SHADER_UNIT 
#define METERS_PER_SHADER_UNIT 100
#endif

#define VOXELS_PER_SHADER_UNIT (VOXELS_PER_METER * METERS_PER_SHADER_UNIT)
#define SHADER_UNIT_PER_VOXEL (1.0 / VOXELS_PER_SHADER_UNIT)

#ifndef GI_ATLAS_SIZE
#define GI_ATLAS_SIZE 64
#endif

#ifndef PROBE_RADIANCE_RES
#define PROBE_RADIANCE_RES 8
#endif

#ifndef PROBE_DEPTH_RES
#define PROBE_DEPTH_RES 8
#endif

#define PROBE_TILE_SIZE PROBE_DEPTH_RES
#define RAYS_PER_TEXEL 1
#define PROBE_PADDING 1
